function [] = motiscanV2020_makeInputText(cfg)
%[] = motiscanV2020_makeInputText(cfg)
% Creates structure savec as .mat file. The structure 'input_texts'
% contains_forOlder all the text that is needed throughout the motivational battery
% scripts. Each function has a dedicated subfield (which name is the name
% of the function (e.g., input_texts.motiscanV2020_init). Each input index
% follows the order of appearance in the script.
%
% by <thelma.landron@gmail.com> on the first day of the Covid-19 lockdown,
% the 17th of March of the year 2020. May the odds be ever in our favour !

% Updated February 2023 for V2023, R.JOLY


input_texts = struct;

%% check_hand
input_texts.check_hand{1,1} = {'left','right'};                                        ...
    input_texts.check_hand{1,2} = {'gauche','droite'};

input_texts.check_hand{2,1} =                                           ...
    ['\nPress [ENTER] to continue ''%s'''                               ...
    ' with the main hand (%s).\nEnter another alphanumeric key to '     ...
    'switch hand otherwise.'];
input_texts.check_hand{2,2} =                                           ...
    ['\nAppuyer sur [ENTREE] pour continuer la tâche ''%s'' avec la '   ...
    'main principale (%s).\nSinon, entrer une autre touche '            ...
    'alphanumérique du clavier pour changer de main.'];

input_texts.check_hand{3,1} =                                           ...
    ['\nPlease confirm hand switching: %s hand for ''%s'' by pressing ' ...
    '[ENTER].'];
input_texts.check_hand{3,2} =                                           ...
    ['\nConfirmer le changement de main : main %s pour la tâche '       ...
    '''%s'' en appuyant sur [ENTREE].'];

input_texts.check_hand{4,1} =                               ...
    ['\nFmax already known, re-calibrate %s hand? (numeric, yes: 1/no: 0): '];
input_texts.check_hand{4,2} =                               ...
    ['\nLa fmax est déjà enregistrée, recalibrer la main %s ? (chiffre, oui : 1/non : 0) : '];

%% check_taskSel
input_texts.check_taskSel{1,1} =                                        ...
    'choice task(s) selected without the related rating task(s).';
input_texts.check_taskSel{1,2} =                                        ...
    ['tâche/s de choix sélectionnées sans la/les tâche/s d''' ...
    'évaluation associée/s.'];

input_texts.check_taskSel{2,1} =                                        ...
    ['Please make sure to select the rating task(s) needed for the '    ...
    'associated choice (1D or 2D) task(s)!\n\n'];
input_texts.check_taskSel{2,2} =                                        ...
    ['Sélectionner la/les tâche/s d''évaluation nécessaire/s '...
    'pour la/les tâche/s de choix (1D ou 2D) associée/s !\n\n'];

%% input_num
input_texts.input_num{1,1} =                                            ...
    ['/!\\/!\\/!\\ Please only type numerical %d or %d in! /!\\/!\\/!\\\n'];
input_texts.input_num{1,2} =                                            ...
    ['/!\\/!\\/!\\ N''entrer qu''un nombre %d ou '  ...
    '%d ! /!\\/!\\/!\\\n'];

input_texts.input_num{2,1} =                                            ...
    ['/!\\/!\\/!\\ Please only type a numeric between %d and %d in! '   ...
    '/!\\/!\\/!\\\n'];
input_texts.input_num{2,2} =                                            ...
    ['/!\\/!\\/!\\ N''entrer que des nombres contenus entre ' ...
    '%d et %d ! /!\\/!\\/!\\\n'];

%% morpho_ask
input_texts.morpho_ask{1,1} =                                           ...
    ['\nMorphology: please provide morphological information about '    ...
    'the hand used for the task(s),\n'                                   ...
    'if these informations are not available just type 0 in to skip '  ...
    'the questions.'];
input_texts.morpho_ask{1,2} =                                           ...
    ['\nMorphologie : informations morphologiques de la main utilisée ' ...
    'pour les tâches de force,\nsi ces informations ne sont pas '        ...
    'disponibles entrer 0.'];

input_texts.morpho_ask{2,1} =                                           ...
    ['\n'                                                               ...
    '  -  forearm anterior skinfold    (mm): '];
input_texts.morpho_ask{2,2} =                                                    ...
    ['\n'                                                               ...
    '  -  pli cutané antérieur de l''avant-bras    (mm) : '];

input_texts.morpho_ask{3,1} =                                                    ...
    ['  -  forearm posterior skinfold   (mm): '];
input_texts.morpho_ask{3,2} =                                                    ...
    ['  -  pli cutané postérieur de l''avant-bras   (mm) : '];

input_texts.morpho_ask{4,1} =                                                    ...
    ['  -  forearm circumference        (mm): '];
input_texts.morpho_ask{4,2} =                                                    ...
    ['  -  circonférence de l''avant-bras           (mm) : '];

input_texts.morpho_ask{5,1} =                                                    ...
    ['  -  forearm length               (mm): '];
input_texts.morpho_ask{5,2} =                                                    ...
    ['  -  longueur de l''avant-bras?               (mm) : '];

%% motiscanV2020_init
input_texts.motiscanV2020_init{1,1} =                                                    ...
    ['============ MOTIscan study selection:\n'                               ...
    '   -   1 for "Vortiobat"\n'                               ...
    '   -   2 for "Motistroke"\n'                                       ...
    '   -   3 for "Ketabi"\n'                                       ...
    '   -   4 for "Conhect"\n'                                       ...
    '   -   5 for "Delai"\n'                                       ...
    '   -   6 for "Cogperf"\n'                                       ...
    '   -   7 for "Pilote"\n'                                       ...
    '   -   8 for "motineuro"\n'                                       ...
    '   -   9 for "ddt"\n'                                       ...
    '   -   10 for "neuroprems"\n'                                       ...
    'Answer (numeric, 1/2/3/4/5/6/7/8/9/10): '];

input_texts.motiscanV2020_init{1,2} =                                                    ...
    ['\n============ Sélection de l''étude MOTIscan :\n'               ...
    '   -   1 pour "Vortiobat"\n'                                        ...
    '   -   2 pour "Motistroke"\n'                                      ...
    '   -   3 pour "Ketabi"\n'                                      ...
    '   -   4 pour "Conhect"\n'                                      ...
    '   -   5 pour "Delai"\n'                                      ...
    '   -   6 pour "Cogperf"\n'                                      ...
    '   -   7 pour "Pilote"\n'                                      ...
    '   -   8 pour "motineuro"\n'                                       ...
    '   -   9 pour "ddt"\n'                                       ...
    '   -   10 pour "neuroprems"\n'                                       ...
    'Réponse (chiffre, 1/2/3/4/5/6/7/8/9/10) : '];

input_texts.motiscanV2020_init{2,1} =                                                    ...
    ['============ MOTIscan study selection: %s ============\n'];
input_texts.motiscanV2020_init{2,2} =                                                    ...
    ['============ Sélection de l''étude MOTIscan : %s ============\n'];

input_texts.motiscanV2020_init{3,1} = '\nSubject identification number (numeric): ';
input_texts.motiscanV2020_init{3,2} =                                                    ...
    ['\nNuméro d''identification du sujet (chiffre) : '];

input_texts.motiscanV2020_init{4,1} = '\nSession number (numeric): ';
input_texts.motiscanV2020_init{4,2} =                                                    ...
    ['\nNuméro de session (chiffre) : '];

input_texts.motiscanV2020_init{5,1} =                                                    ...
    ['\nAvailable data for subject %d, session %d: %s (yyyymmdd).\n'    ...
    'Loaded in structure ''tmp''.\n'               ...
    'Do you want to continue with the available data?\n'               ...
    '   Answer (numeric, yes: 1/no: 0): '];
input_texts.motiscanV2020_init{5,2} =                                                    ...
    ['\nDonnées et configuration existantes pour le sujet %d, session %d:'...
    ' %s (aaaammjj).\nChargement dans la structure ''tmp'''     ...
    '...\nContinuer avec la configuration et les ' ...
    'données déjà disponibles ?\n   Réponse (chiffre, oui : 1/non : 0) : '];

input_texts.motiscanV2020_init{6,1} = '%s, restarting session %d for subject %d!';
input_texts.motiscanV2020_init{6,2} = '%s, session %d du sujet %d recommencée !';

input_texts.motiscanV2020_init{7,1} = 'Already selected tasks:\n%s\nContinue with them? (numeric, yes: 1/no: 0): ';
input_texts.motiscanV2020_init{7,2} = 'Tâches déjà sélectionnées :\n%s\nContinuer avec ? (chiffre, oui : 1/non : 0) : ';

input_texts.motiscanV2020_init{8,1} = 'Two different ID codes for subject %d, ''%s'' (previous) vs. ''%s''!';
input_texts.motiscanV2020_init{8,2} = 'Deux codes ID différents pour le sujet %d, ''%s'' (ancien) vs. ''%s'' !';

input_texts.motiscanV2020_init{9,1} = 'Which one to be kept, ''%s'': 0/''%s'': 1 (or esc: 2) ';
input_texts.motiscanV2020_init{9,2} = 'A conserver, ''%s'' : 0/''%s'' : 1 (ou esc: 2) ';

input_texts.motiscanV2020_init{10,1} = 'user escaping (wrong subject''s ID code)';
input_texts.motiscanV2020_init{10,2} = 'arrêt utilisateur (erreur code ID sujet) ';

%% motiscanV2020_run
input_texts.motiscanV2020_run{1,1} =                                       ...
    ['\nPre-determined task selection for %s, #1-18:\n'                   ...
    '   -   Response device training;\n'                                ...
    '   -   Ratings RPE;\n'                                             ...
    '   -   Choices (1D & 2D) RPE;\n'                                   ...
    '   -   Money discounting (risk, delay, mental & physical effort);\n'...
    '   -   Physical effort rating (grip);\n'                                    ...
    '   -   Confidence precision;\n'                                    ...
    '   -   Physical (grip) & mental effort test.\n'                               ...
    'Continue with this pre-determined task selection, #1-18 '          ...
    '(yes: 1/no: 0): '];
input_texts.motiscanV2020_run{1,2} =                                       ...
    ['\nSélection des tâches pré-déterminée pour %s, n°1-18 :\n'        ...
    '   -   Entraînement au dispositif de réponse ;\n'                 ...
    '   -   Evaluations RPE ;\n'                                        ...
    '   -   Choix (1D & 2D) RPE ;\n'                                    ...
    '   -   Décomptes monétaires (risque & délai, effort mental & physique) ;\n'...
    '   -   Evaluation d''effort physique (grip) ;\n'       ...
    '   -   Confiance de précision ;\n'                                 ...
    '   -   Test d''effort physique (grip) & mental.\n'                ...
    'Continuer avec les tâches pré-déterminées, n°1-18 '               ...
    '(oui : 1/non : 0): '];

input_texts.motiscanV2020_run{2,1} =                                       ...
    ['\nPre-determined task selection for %s, #1-12,14-15:\n'            ...
    '   -   Response device training;\n'                                ...
    '   -   Ratings RPE;\n'                                             ...
    '   -   Choices (1D & 2D) RPE;\n'                                   ...
    '   -   Money discounting (risk, delay & physical effort);\n'                        ...
    '   -   Physical effort rating (grip);\n'                                     ...
    'Continue with pre-determined task selection, #1-12,14-15 '          ...
    '(yes: 1/no: 0): '];
input_texts.motiscanV2020_run{2,2} =                                    ...
    ['\nSélection des tâches pré-déterminée pour %s, n°1-12,14-15 :\n'   ...
    '   -   Entraînement au dispositif de réponse ;\n'                  ...
    '   -   Evaluations RPE ;\n'                                        ...
    '   -   Choix (1D & 2D) RPE ;\n'                                    ...
    '   -   Décomptes monétaires (risque, délai & effort physique) ;\n'          ...
    '   -   Evaluation d''effort physique (grip) ;\n'                   ...
    'Continuer avec les tâches pré-déterminées, n°1-12,14-15 '          ...
    '(oui : 1/non : 0): '];

input_texts.motiscanV2020_run{3,1} =                                                    ...
    ['\nTasks selection:\n'...
    '   - %d for "Resp. device training"\n'...
    '   - %d for "Rating R"\n'         ...
    '   - %d for "Rating P"\n'         ...
    '   - %d for "Rating E"\n'         ...
    '   - %d for "Choice 1D (RR)"\n'   ...
    '   - %d for "Choice 1D (PP)"\n'   ...
    '   - %d for "Choice 1D (EE)"\n'   ...
    '   - %d for "Choice 2D (RE)"\n'   ...
    '   - %d for "Choice 2D (PE)"\n'   ...
    '   - %d for "Choice 2D (RP)"\n'   ...
    '   - %d for "Money discounting (delay)"\n' ...
    '   - %d for "Money discounting (risk)"\n'  ...
    '   - %d for "Money discounting (mental effort)"\n'...
    '   - %d for "Money discounting (physical effort)"\n'...
    '   - %d for "Physical effort rating (grip)"\n'      ...
    '   - %d for "Confidence precision"\n'      ...
    '   - %d for "Physical effort test (grip)"\n' ...
    '   - %d for "Mental effort test"\n'    ...
    'Answer (numeric, %d:%d): '];
input_texts.motiscanV2020_run{3,2} =                                                    ...
    ['\nSélection des tâches:\n'...
    '   - %d pour "Entraînement dispositif de réponse"\n'...
    '   - %d pour "Evaluation R"\n'         ...
    '   - %d pour "Evaluation P"\n'         ...
    '   - %d pour "Evaluation E"\n'         ...
    '   - %d pour "Choix 1D (RR)"\n'   ...
    '   - %d pour "Choix 1D (PP)"\n'   ...
    '   - %d pour "Choix 1D (EE)"\n'   ...
    '   - %d pour "Choix 2D (RE)"\n'   ...
    '   - %d pour "Choix 2D (PE)"\n'   ...
    '   - %d pour "Choix 2D (RP)"\n'   ...
    '   - %d pour "Décompte monétaire (delai)"\n' ...
    '   - %d pour "Décompte monétaire (risque)"\n'  ...
    '   - %d pour "Décompte monétaire (effort mental)"\n'  ...
    '   - %d pour "Décompte monétaire (effort physique)"\n' ...
    '   - %d pour "Evaluation d''effort physique (grip)"\n'      ...
    '   - %d pour "Confiance de précision"\n'      ...
    '   - %d pour "Test d''effort physique (grip)"\n'                 ...
    '   - %d pour "Test d''effort mental"\n'    ...
    'Réponse (chiffre, %d:%d) : '];

input_texts.motiscanV2020_run{4,1} =                                       ...
    ['\nThe next task has already been completed, but you can do it '   ...
    ' again if needed.\n'];
input_texts.motiscanV2020_run{4,2} =                                       ...
    ['\nLa tâche suivante a déjà été réalisée, mais il est possible de ' ...
    'la refaire si besoin.\n'];

input_texts.motiscanV2020_run{5,1} =                                       ...
    ['Start ''%s'' (no: 0/yes: 1/esc: 2): '];
input_texts.motiscanV2020_run{5,2} =                                       ...
    ['Commencer ''%s'' (non : 0/oui : 1/esc : 2) : '];     ...

input_texts.motiscanV2020_run{7,1} =                                       ...
    ['\nPre-determined task selection for %s, #1,19-26,29-33:\n'          ...
    '   -   Response device training;\n'                                ...
    '   -   Ratings NR2E2S;\n'                                        ...
    '   -   Choice 1D;\n'                                        ...                                        ...
    '   -   Choice 4D NRAS"\n'                                       ...
    'Continue with this pre-determined task selection, #1,19-26,29-33 '          ...
    '(yes: 1/no: 0): '];

input_texts.motiscanV2020_run{7,2} =                                       ...
    ['\nSélection des tâches pré-déterminée pour %s, n°1,19-26,29-33:\n'        ...
    '   -   Entrainement au dispositif de réponse ;\n'                 ...
    '   -   Evaluations NR2E2S ;\n'                ...
    '   -   Choix 1D;\n'                                           ...                                           ...
    '   -   Choix 4D NRAS"\n'                             ...
    'Continuer avec les tâches pré-déterminées, n°1,19-26,29-33 '               ...
    '(oui : 1/non : 0): '];

input_texts.motiscanV2020_run{8,1} =            ...
 ['\nTasks selection:\n'                    ...
    '   - %d for "Resp. device training"\n'...
    '   - %d for "Rating N"\n'         ...
    '   - %d for "Rating R2"\n'         ...
    '   - %d for "Rating E2"\n'         ...
    '   - %d for "Rating S"\n'         ...
    '   - %d for "Choice 1D NN"\n'    ...
    '   - %d for "Choice 1D E2E2"\n'    ...
    '   - %d for "Choice 1D R2R2"\n'    ...
    '   - %d for "Choice 3D NR2S"\n'    ...
    '   - %d for "Perception Control Task"\n'    ...
    '   - %d for "Semantic Control Task"\n'    ...
    '   - %d for "TOM Control Task"\n'    ...
    'Answer (numeric, %d:%d): '];       ...

input_texts.motiscanV2020_run{8,2} =                    ...  
['\nSélection des tâches:\n'...
    '   - %d pour "Entraînement dispositif de réponse"\n'...
    '   - %d pour "Evaluation N"\n'         ...
    '   - %d pour "Evaluation R2"\n'         ...
    '   - %d pour "Evaluation E2"\n'         ...    
    '   - %d pour "Evaluation S"\n'         ...
    '   - %d pour "Choix 1D NN"\n'         ...
    '   - %d pour "Choix 1D E2E2"\n'         ...
    '   - %d pour "Choix 1D R2R2"\n'         ...
    '   - %d pour "Choix 3D NR2S"\n'    ...
    '   - %d pour "Tâche contrôle de perception"\n'    ...
    '   - %d pour "Tâche contrôle Sémantique"\n'    ...
    '   - %d pour "Tâche contrôle Théorie de l''esprit"\n'    ...
    'Réponse (chiffre, %d:%d) : '];


% minimal task selection text (for e.g. CONHECT AND DELAI)
input_texts.motiscanV2020_run{6,1} =                                       ...
    ['\nContinue with pre-determined task selection? '                      ...
    '(yes: 1 / no: 0): '];
input_texts.motiscanV2020_run{6,2} =                                       ...
    ['\nContinuer avec les tâches pré-déterminées ? '                       ...
    '(oui : 1 / non : 0): '];




%% motiscanV2020_setHandGrip
input_texts.motiscanV2020_setHandGrip{1,1} =                               ...
    ['\nDominant (or mainly used) hand? (numeric, left: 1/right: 2): '];
input_texts.motiscanV2020_setHandGrip{1,2} =                               ...
    ['\nMain dominante (ou principalement utilisée) ? (chiffre, gauche : 1/droite : 2) : '];

input_texts.motiscanV2020_setHandGrip{2,1} = {'left','right'};
input_texts.motiscanV2020_setHandGrip{2,2} = {'gauche','droite'};

input_texts.motiscanV2020_setHandGrip{3,1} =                               ...
    ['\nFmax already known, re-calibrate %s hand? (numeric, yes: 1/no: 0): '];
input_texts.motiscanV2020_setHandGrip{3,2} =                               ...
    ['\nLa fmax est déjà enregistrée, recalibrer la main %s ? (chiffre, oui : 1/non : 0) : '];

input_texts.motiscanV2020_setHandGrip{4,1} =                               ...
    ['\nWill the other (%s) hand be used? (numeric, yes: 1/no: 0): '];
input_texts.motiscanV2020_setHandGrip{4,2} =                               ...
    ['\nL''autre main (%s) sera-t-elle utilisée ? (chiffre, oui : 1/non : 0) : '];

%% motiscanV2020_setPTB
input_texts.motiscanV2020_setPTB{1,1} = ['\nWill you use the touchscreen ?'...
    ' (numeric, yes: 1/no: 0): '];
input_texts.motiscanV2020_setPTB{1,2} = ['\nL''écran tactile '   ...
    'sera-t-il utilisé ? (chiffre, oui : 1/ non : 0) : '];
input_texts.motiscanV2020_setPTB{2,1} =                                    ...
    ['\n=========== Psychtoolbox correctly configured, tasks beginning ===========\n\n'];
input_texts.motiscanV2020_setPTB{2,2} =                                    ...
    ['\n=========== Psychtoolbox correctement configurée, début des tâches ===========\n\n'];

%% tasks_order
input_texts.tasks_order{1,1} =                                          ...
    ['\nOrder 1D-task(s): ''%s''.\n'];
input_texts.tasks_order{1,2} =                                          ...
    ['\nOrdre des tâches 1D : ''%s''.\n'];

input_texts.tasks_order{2,1} =                                          ...
    ['\nOrder 1D-task: only one dimension selected (''%s'''     ...
    ').\n'];
input_texts.tasks_order{2,2} =                                          ...
    ['\nOrdre des tâches 1D : une seule dimension sélectionnée ('       ...
    '''%s'').\n'];

input_texts.tasks_order{3,1} =                                          ...
    ['Order 2D-task(s): ''%s''.\n'];
input_texts.tasks_order{3,2} =                                          ...
    ['Ordre des tâches 2D : ''%s''.\n'];

input_texts.tasks_order{4,1} =                                          ...
    ['Order 2D-task: only one task selected (''%s'').\n'];
input_texts.tasks_order{4,2} =                                          ...
    ['Ordre des tâches 2D : une seule tâche sélectionnée (''%s'').\n'];

input_texts.tasks_order{5,1} =                                          ...
    ['Order money-task(s): ''%s''.\n'];
input_texts.tasks_order{5,2} =                                          ...
    ['Ordre des tâches de décompte monétaire : ''%s''.\n'];

input_texts.tasks_order{6,1} =                                          ...
    ['Order money-task: one task selected (''%s'').\n'];
input_texts.tasks_order{6,2} =                                          ...
    ['Ordre des tâches de décompte monétaire : une seule tâche '        ...
    'sélectionnée (''%s'').\n'];

input_texts.tasks_order{7,1} =                                          ...
    ['Order effort-task(s): ''%s''.\n'];
input_texts.tasks_order{7,2} =                                          ...
    ['Ordre des tâches d''effort : ''%s''.\n'];

input_texts.tasks_order{8,1} =                                          ...
    ['Order effor-task: only one task selected ''%s''.\n'];
input_texts.tasks_order{8,2} =                                          ...
    ['Ordre des tâches d''effort : une seule tâche sélectionnée ''%s''.\n'];

%% saving in .mat
save([cfg.paths.task.code 'motiscanV2020_inputText'], 'input_texts')

end